## Preprocessing

In [5]:
pip install tensorflow

Requirement already satisfied: tensorflow in /Users/gigi/anaconda3/lib/python3.11/site-packages (2.15.0)
Requirement already satisfied: tensorflow-macos==2.15.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow) (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (3.7.0)
Requirement already satisfied: libclang>=13.0.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.24.3)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (3.3.0)
Requirement already satisfied: packaging in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (23.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (4.25.3)
Requirement already satisfied: setuptools in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (68.0.0)
Requirement already satisfied: six>=1.12.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (4.7.1)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.62.0)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow-macos==2.15.0->tensorflow) (0.38.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.28.1)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.2.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.1.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /Users/gigi/anaconda3/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (3.2.2)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE

application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [8]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE

unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [9]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE

application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [10]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

cutoff = 737

application_types_to_replace = list(application_type_counts[application_type_counts<cutoff].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
Other     1529
T6        1216
T5        1173
T19       1065
T8         737
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE

classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [13]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

classification_counts_filtered = classification_counts[classification_counts>1]
classification_counts_filtered

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [17]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

c_cutoff = 377

classifications_to_replace = list(classification_counts[classification_counts<c_cutoff].index)


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [18]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

application_df_encoded = pd.get_dummies(application_df)
application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T8,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [19]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE

X = application_df_encoded.drop('IS_SUCCESSFUL', axis=1)
y = application_df_encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=37)

In [20]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [22]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()
input_features = X_train.shape [1]
hidden_layer1_neurons = 80
hidden_layer2_neurons = 30


# First hidden layer
# YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_layer1_neurons, input_dim=input_features, activation='relu'))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_layer2_neurons, activation='relu'))

# Output layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 80)                3440

 dense_2 (Dense)             (None, 30)                2430

 dense_3 (Dense)             (None, 1)                 31

=================================================================
Total params: 5901 (23.05 KB)
Trainable params: 5901 (23.05 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
# Compile the model
#  YOUR CODE GOES HERE

nn.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

In [24]:
# Train the model
#  YOUR CODE GOES HERE

model_train = nn.fit(X_train, y_train, epochs=100, verbose=1, validation_data=(X_test, y_test))

Epoch 1/100
804/804 [==============================] - 1s 542us/step - loss: 40874.7812 - accuracy: 0.4877 - val_loss: 35358.5898 - val_accuracy: 0.5340
Epoch 2/100
804/804 [==============================] - 0s 457us/step - loss: 20364.8633 - accuracy: 0.4943 - val_loss: 27599.8770 - val_accuracy: 0.4660
Epoch 3/100
804/804 [==============================] - 0s 450us/step - loss: 23374.5977 - accuracy: 0.4944 - val_loss: 35839.1914 - val_accuracy: 0.4659
Epoch 4/100
804/804 [==============================] - 0s 453us/step - loss: 11307.6699 - accuracy: 0.4988 - val_loss: 203.3160 - val_accuracy: 0.5177
Epoch 5/100
804/804 [==============================] - 0s 495us/step - loss: 19473.2168 - accuracy: 0.4951 - val_loss: 31848.8672 - val_accuracy: 0.4659
Epoch 6/100
804/804 [==============================] - 0s 450us/step - loss: 14406.1816 - accuracy: 0.5078 - val_loss: 43499.9180 - val_accuracy: 0.5747
Epoch 7/100
804/804 [==============================] - 0s 449us/step - loss: 12448.5605 - accuracy: 0.5063 - val_loss: 17163.9863 - val_accuracy: 0.4659
Epoch 8/100
804/804 [==============================] - 0s 450us/step - loss: 11442.7061 - accuracy: 0.5122 - val_loss: 27999.1660 - val_accuracy: 0.4659
Epoch 9/100
804/804 [==============================] - 0s 449us/step - loss: 9570.6748 - accuracy: 0.5042 - val_loss: 42710.9180 - val_accuracy: 0.5340
Epoch 10/100
804/804 [==============================] - 0s 449us/step - loss: 8563.8164 - accuracy: 0.5145 - val_loss: 9488.2539 - val_accuracy: 0.5340
Epoch 11/100
804/804 [==============================] - 0s 450us/step - loss: 4358.7334 - accuracy: 0.5066 - val_loss: 923.1638 - val_accuracy: 0.6237
Epoch 12/100
804/804 [==============================] - 0s 451us/step - loss: 4486.1006 - accuracy: 0.5114 - val_loss: 29356.3418 - val_accuracy: 0.5340
Epoch 13/100
804/804 [==============================] - 0s 488us/step - loss: 5706.7119 - accuracy: 0.5074 - val_loss: 7176.1123 - val_accuracy: 0.4659
Epoch 14/100
804/804 [==============================] - 0s 454us/step - loss: 1969.1624 - accuracy: 0.5139 - val_loss: 9184.9863 - val_accuracy: 0.5341
Epoch 15/100
804/804 [==============================] - 0s 457us/step - loss: 5252.1582 - accuracy: 0.4956 - val_loss: 16332.7363 - val_accuracy: 0.4659
Epoch 16/100
804/804 [==============================] - 0s 453us/step - loss: 3194.6199 - accuracy: 0.5081 - val_loss: 1923.6304 - val_accuracy: 0.5340
Epoch 17/100
804/804 [==============================] - 0s 448us/step - loss: 352.4612 - accuracy: 0.5319 - val_loss: 0.7734 - val_accuracy: 0.5341
Epoch 18/100
804/804 [==============================] - 0s 450us/step - loss: 4416.7490 - accuracy: 0.5316 - val_loss: 6345.9980 - val_accuracy: 0.5290
Epoch 19/100
804/804 [==============================] - 0s 452us/step - loss: 1391.4242 - accuracy: 0.5313 - val_loss: 0.6938 - val_accuracy: 0.5341
Epoch 20/100
804/804 [==============================] - 0s 451us/step - loss: 1875.7812 - accuracy: 0.5323 - val_loss: 1652.2198 - val_accuracy: 0.5340
Epoch 21/100
804/804 [==============================] - 0s 452us/step - loss: 251.4908 - accuracy: 0.5320 - val_loss: 2.2470 - val_accuracy: 0.5341
Epoch 22/100
804/804 [==============================] - 0s 490us/step - loss: 4015.5586 - accuracy: 0.5312 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 23/100
804/804 [==============================] - 0s 450us/step - loss: 1371.1637 - accuracy: 0.5318 - val_loss: 2180.5867 - val_accuracy: 0.5340
Epoch 24/100
804/804 [==============================] - 0s 452us/step - loss: 546.3432 - accuracy: 0.5318 - val_loss: 4054.7241 - val_accuracy: 0.5340
Epoch 25/100
804/804 [==============================] - 0s 452us/step - loss: 615.5770 - accuracy: 0.5319 - val_loss: 1435.3601 - val_accuracy: 0.5340
Epoch 26/100
804/804 [==============================] - 0s 454us/step - loss: 223.9006 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 27/100
804/804 [==============================] - 0s 450us/step - loss: 623.3682 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 28/100
804/804 [==============================] - 0s 452us/step - loss: 749.2882 - accuracy: 0.5318 - val_loss: 803.8669 - val_accuracy: 0.5340
Epoch 29/100
804/804 [==============================] - 0s 457us/step - loss: 1618.4380 - accuracy: 0.5318 - val_loss: 2746.9329 - val_accuracy: 0.5340
Epoch 30/100
804/804 [==============================] - 0s 451us/step - loss: 566.1591 - accuracy: 0.5318 - val_loss: 2298.7573 - val_accuracy: 0.5340
Epoch 31/100
804/804 [==============================] - 0s 489us/step - loss: 349.2466 - accuracy: 0.5319 - val_loss: 687.1306 - val_accuracy: 0.5340
Epoch 32/100
804/804 [==============================] - 0s 451us/step - loss: 104.8055 - accuracy: 0.5319 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 33/100
804/804 [==============================] - 0s 451us/step - loss: 311.7984 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 34/100
804/804 [==============================] - 0s 451us/step - loss: 58.2842 - accuracy: 0.5318 - val_loss: 1469.2305 - val_accuracy: 0.5340
Epoch 35/100
804/804 [==============================] - 0s 451us/step - loss: 224.9579 - accuracy: 0.5318 - val_loss: 195.8363 - val_accuracy: 0.5340
Epoch 36/100
804/804 [==============================] - 0s 452us/step - loss: 40.7316 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 37/100
804/804 [==============================] - 0s 452us/step - loss: 479.4354 - accuracy: 0.5319 - val_loss: 910.3768 - val_accuracy: 0.5340
Epoch 38/100
804/804 [==============================] - 0s 450us/step - loss: 138.6662 - accuracy: 0.5319 - val_loss: 18.8298 - val_accuracy: 0.5340
Epoch 39/100
804/804 [==============================] - 0s 484us/step - loss: 265.2730 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 40/100
804/804 [==============================] - 0s 451us/step - loss: 35.8152 - accuracy: 0.5318 - val_loss: 7.0086 - val_accuracy: 0.5340
Epoch 41/100
804/804 [==============================] - 0s 452us/step - loss: 1.6493 - accuracy: 0.5319 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 42/100
804/804 [==============================] - 0s 451us/step - loss: 0.7325 - accuracy: 0.5319 - val_loss: 1.0458 - val_accuracy: 0.5340
Epoch 43/100
804/804 [==============================] - 0s 453us/step - loss: 0.7449 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 44/100
804/804 [==============================] - 0s 453us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 45/100
804/804 [==============================] - 0s 453us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 46/100
804/804 [==============================] - 0s 458us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 47/100
804/804 [==============================] - 0s 453us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 48/100
804/804 [==============================] - 0s 491us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 49/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 50/100
804/804 [==============================] - 0s 452us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 51/100
804/804 [==============================] - 0s 452us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 52/100
804/804 [==============================] - 0s 452us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 53/100
804/804 [==============================] - 0s 454us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 54/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 55/100
804/804 [==============================] - 0s 452us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 56/100
804/804 [==============================] - 0s 490us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 57/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 58/100
804/804 [==============================] - 0s 453us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 59/100
804/804 [==============================] - 0s 460us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 60/100
804/804 [==============================] - 0s 452us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 61/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 62/100
804/804 [==============================] - 0s 452us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 63/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6909 - val_accuracy: 0.5341
Epoch 64/100
804/804 [==============================] - 0s 487us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 65/100
804/804 [==============================] - 0s 452us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 66/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 67/100
804/804 [==============================] - 0s 450us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6909 - val_accuracy: 0.5341
Epoch 68/100
804/804 [==============================] - 0s 454us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 69/100
804/804 [==============================] - 0s 450us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 70/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 71/100
804/804 [==============================] - 0s 450us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 72/100
804/804 [==============================] - 0s 486us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 73/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 74/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 75/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 76/100
804/804 [==============================] - 0s 457us/step - loss: 0.6912 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5341
Epoch 77/100
804/804 [==============================] - 0s 453us/step - loss: 0.6911 - accuracy: 0.5318 - val_loss: 0.6908 - val_accuracy: 0.5340
Epoch 78/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6908 - val_accuracy: 0.5340
Epoch 79/100
804/804 [==============================] - 0s 479us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 80/100
804/804 [==============================] - 0s 449us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 81/100
804/804 [==============================] - 0s 450us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6908 - val_accuracy: 0.5340
Epoch 82/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 83/100
804/804 [==============================] - 0s 448us/step - loss: 0.6912 - accuracy: 0.5319 - val_loss: 0.6908 - val_accuracy: 0.5340
Epoch 84/100
804/804 [==============================] - 0s 450us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 85/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 86/100
804/804 [==============================] - 0s 454us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 87/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 88/100
804/804 [==============================] - 0s 489us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 89/100
804/804 [==============================] - 0s 450us/step - loss: 0.6912 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 90/100
804/804 [==============================] - 0s 450us/step - loss: 0.6912 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 91/100
804/804 [==============================] - 0s 451us/step - loss: 0.6912 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 92/100
804/804 [==============================] - 0s 453us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 93/100
804/804 [==============================] - 0s 450us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 94/100
804/804 [==============================] - 0s 459us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 95/100
804/804 [==============================] - 0s 483us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 96/100
804/804 [==============================] - 0s 451us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 97/100
804/804 [==============================] - 0s 452us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 98/100
804/804 [==============================] - 0s 456us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 99/100
804/804 [==============================] - 0s 455us/step - loss: 0.6912 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340
Epoch 100/100
804/804 [==============================] - 0s 450us/step - loss: 0.6911 - accuracy: 0.5319 - val_loss: 0.6909 - val_accuracy: 0.5340

In [25]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.9106 - accuracy: 0.4797 - 108ms/epoch - 405us/step
Loss: 0.9106089472770691, Accuracy: 0.4796501398086548

In [27]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE

nn.save("alphabetSoupCharity.h5")